# This file has been generated by node2nix 1.1.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "generator-reveal-1.0.0" = {
      name = "generator-reveal";
      packageName = "generator-reveal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generator-reveal/-/generator-reveal-1.0.0.tgz";
        sha1 = "b30c51460a260e375329a55b003ae7c53d35b440";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "underscore.string-3.3.4" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-3.3.4.tgz";
        sha1 = "2c2a3f9f83e64762fdc45e6ceac65142864213db";
      };
    };
    "yeoman-generator-1.1.1" = {
      name = "yeoman-generator";
      packageName = "yeoman-generator";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yeoman-generator/-/yeoman-generator-1.1.1.tgz";
        sha1 = "40c2b4f6cdfbe05e1952fdd72933f0d8925dbdf5";
      };
    };
    "yosay-1.2.1" = {
      name = "yosay";
      packageName = "yosay";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yosay/-/yosay-1.2.1.tgz";
        sha1 = "9466ef969830e85b474e267b50f7688693ed3b5b";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "async-2.1.5" = {
      name = "async";
      packageName = "async";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.1.5.tgz";
        sha1 = "e587c68580994ac67fc56ff86d3ac56bdbe810bc";
      };
    };
    "class-extend-0.1.2" = {
      name = "class-extend";
      packageName = "class-extend";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/class-extend/-/class-extend-0.1.2.tgz";
        sha1 = "8057a82b00f53f82a5d62c50ef8cffdec6fabc34";
      };
    };
    "cli-table-0.3.1" = {
      name = "cli-table";
      packageName = "cli-table";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz";
        sha1 = "f53b05266a8b1a0b934b3d0821e6e2dc5914ae23";
      };
    };
    "cross-spawn-5.1.0" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-5.1.0.tgz";
        sha1 = "e8bd0efee58fcff6f8f94510a0a554bbfa235449";
      };
    };
    "dargs-5.1.0" = {
      name = "dargs";
      packageName = "dargs";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dargs/-/dargs-5.1.0.tgz";
        sha1 = "ec7ea50c78564cd36c9d5ec18f66329fade27829";
      };
    };
    "dateformat-2.0.0" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-2.0.0.tgz";
        sha1 = "2743e3abb5c3fc2462e527dca445e04e9f4dee17";
      };
    };
    "debug-2.6.1" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.1.tgz";
        sha1 = "79855090ba2c4e3115cc7d8769491d58f0491351";
      };
    };
    "detect-conflict-1.0.1" = {
      name = "detect-conflict";
      packageName = "detect-conflict";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-conflict/-/detect-conflict-1.0.1.tgz";
        sha1 = "088657a66a961c05019db7c4230883b1c6b4176e";
      };
    };
    "error-7.0.2" = {
      name = "error";
      packageName = "error";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error/-/error-7.0.2.tgz";
        sha1 = "a5f75fff4d9926126ddac0ea5dc38e689153cb02";
      };
    };
    "find-up-2.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-2.1.0.tgz";
        sha1 = "45d1b7e506c717ddd482775a2b77920a3c0c57a7";
      };
    };
    "github-username-3.0.0" = {
      name = "github-username";
      packageName = "github-username";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/github-username/-/github-username-3.0.0.tgz";
        sha1 = "0a772219b3130743429f2456d0bdd3db55dce7b1";
      };
    };
    "glob-7.1.1" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.1.tgz";
        sha1 = "805211df04faaf1c63a3600306cdf5ade50b2ec8";
      };
    };
    "istextorbinary-2.1.0" = {
      name = "istextorbinary";
      packageName = "istextorbinary";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/istextorbinary/-/istextorbinary-2.1.0.tgz";
        sha1 = "dbed2a6f51be2f7475b68f89465811141b758874";
      };
    };
    "mem-fs-editor-3.0.2" = {
      name = "mem-fs-editor";
      packageName = "mem-fs-editor";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mem-fs-editor/-/mem-fs-editor-3.0.2.tgz";
        sha1 = "dd0a6eaf2bb8a6b37740067aa549eb530105af9f";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "pretty-bytes-4.0.2" = {
      name = "pretty-bytes";
      packageName = "pretty-bytes";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-bytes/-/pretty-bytes-4.0.2.tgz";
        sha1 = "b2bf82e7350d65c6c33aa95aaa5a4f6327f61cd9";
      };
    };
    "read-chunk-2.0.0" = {
      name = "read-chunk";
      packageName = "read-chunk";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-chunk/-/read-chunk-2.0.0.tgz";
        sha1 = "3246e877829116cec059674c4d5f300f7a9261f3";
      };
    };
    "read-pkg-up-2.0.0" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-2.0.0.tgz";
        sha1 = "6b72a8048984e0c41e79510fd5e9fa99b3b549be";
      };
    };
    "rimraf-2.6.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.1.tgz";
        sha1 = "c2338ec643df7a1b7fe5c54fa86f57428a55f33d";
      };
    };
    "run-async-2.3.0" = {
      name = "run-async";
      packageName = "run-async";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-2.3.0.tgz";
        sha1 = "0371ab4ae0bdd720d4166d7dfda64ff7a445a6c0";
      };
    };
    "shelljs-0.7.6" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.7.6.tgz";
        sha1 = "379cccfb56b91c8601e4793356eb5382924de9ad";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "through2-2.0.3" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.3.tgz";
        sha1 = "0004569b37c7c74ba39c43f3ced78d1ad94140be";
      };
    };
    "user-home-2.0.0" = {
      name = "user-home";
      packageName = "user-home";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/user-home/-/user-home-2.0.0.tgz";
        sha1 = "9c70bfd8169bc1dcbf48604e0f04b8b49cde9e9f";
      };
    };
    "yeoman-environment-1.6.6" = {
      name = "yeoman-environment";
      packageName = "yeoman-environment";
      version = "1.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/yeoman-environment/-/yeoman-environment-1.6.6.tgz";
        sha1 = "cd85fa67d156060e440d7807d7ef7cf0d2d1d671";
      };
    };
    "object-assign-2.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-2.1.1.tgz";
        sha1 = "43c36e5d569ff8e4816c4efa8be02d26967c18aa";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "lru-cache-4.0.2" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.0.2.tgz";
        sha1 = "1d17679c069cda5d040991a09dbc2c0db377e55e";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "which-1.2.12" = {
      name = "which";
      packageName = "which";
      version = "1.2.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.2.12.tgz";
        sha1 = "de67b5e450269f194909ef23ece4ebe416fa1192";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "yallist-2.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.0.0.tgz";
        sha1 = "306c543835f09ee1a4cb23b7bce9ab341c91cdd4";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "isexe-1.1.2" = {
      name = "isexe";
      packageName = "isexe";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-1.1.2.tgz";
        sha1 = "36f3e22e60750920f5e7241a476a8c6a42275ad0";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "string-template-0.2.1" = {
      name = "string-template";
      packageName = "string-template";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-template/-/string-template-0.2.1.tgz";
        sha1 = "42932e598a352d01fc22ec3367d9d84eec6c9add";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "locate-path-2.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-2.0.0.tgz";
        sha1 = "2b568b265eec944c6d9c0de9c3dbbbca0354cd8e";
      };
    };
    "p-locate-2.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-2.0.0.tgz";
        sha1 = "20a0103b222a70c8fd39cc2e580680f3dde5ec43";
      };
    };
    "p-limit-1.1.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-1.1.0.tgz";
        sha1 = "b07ff2d9a5d88bec806035895a2bab66a27988bc";
      };
    };
    "gh-got-5.0.0" = {
      name = "gh-got";
      packageName = "gh-got";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gh-got/-/gh-got-5.0.0.tgz";
        sha1 = "ee95be37106fd8748a96f8d1db4baea89e1bfa8a";
      };
    };
    "got-6.7.1" = {
      name = "got";
      packageName = "got";
      version = "6.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-6.7.1.tgz";
        sha1 = "240cd05785a9a18e561dc1b44b41c763ef1e8db0";
      };
    };
    "is-plain-obj-1.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-1.1.0.tgz";
        sha1 = "71a50c8429dfca773c92a390a4a03b39fcd51d3e";
      };
    };
    "create-error-class-3.0.2" = {
      name = "create-error-class";
      packageName = "create-error-class";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-error-class/-/create-error-class-3.0.2.tgz";
        sha1 = "06be7abef947a3f14a30fd610671d401bca8b7b6";
      };
    };
    "duplexer3-0.1.4" = {
      name = "duplexer3";
      packageName = "duplexer3";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.4.tgz";
        sha1 = "ee01dd1cac0ed3cbc7fdbea37dc0a8f1ce002ce2";
      };
    };
    "get-stream-3.0.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-3.0.0.tgz";
        sha1 = "8e943d1358dc37555054ecbe2edb05aa174ede14";
      };
    };
    "is-redirect-1.0.0" = {
      name = "is-redirect";
      packageName = "is-redirect";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-redirect/-/is-redirect-1.0.0.tgz";
        sha1 = "1d03dded53bd8db0f30c26e4f95d36fc7c87dc24";
      };
    };
    "is-retry-allowed-1.1.0" = {
      name = "is-retry-allowed";
      packageName = "is-retry-allowed";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-retry-allowed/-/is-retry-allowed-1.1.0.tgz";
        sha1 = "11a060568b67339444033d0125a61a20d564fb34";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "lowercase-keys-1.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz";
        sha1 = "4e3366b39e7f5457e35f1324bdf6f88d0bfc7306";
      };
    };
    "safe-buffer-5.0.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.0.1.tgz";
        sha1 = "d263ca54696cd8a306b5ca6551e92de57918fbe7";
      };
    };
    "timed-out-4.0.1" = {
      name = "timed-out";
      packageName = "timed-out";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/timed-out/-/timed-out-4.0.1.tgz";
        sha1 = "f32eacac5a175bea25d7fab565ab3ed8741ef56f";
      };
    };
    "unzip-response-2.0.1" = {
      name = "unzip-response";
      packageName = "unzip-response";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unzip-response/-/unzip-response-2.0.1.tgz";
        sha1 = "d2f0f737d16b0615e72a6935ed04214572d56f97";
      };
    };
    "url-parse-lax-1.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-1.0.0.tgz";
        sha1 = "7af8f303645e9bd79a272e7a14ac68bc0609da73";
      };
    };
    "capture-stack-trace-1.0.0" = {
      name = "capture-stack-trace";
      packageName = "capture-stack-trace";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/capture-stack-trace/-/capture-stack-trace-1.0.0.tgz";
        sha1 = "4a6fa07399c26bba47f0b2496b4d0fb408c5550d";
      };
    };
    "prepend-http-1.0.4" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz";
        sha1 = "d4f4562b0ce3696e41ac52d0e002e57a635dc6dc";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "textextensions-2.0.1" = {
      name = "textextensions";
      packageName = "textextensions";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/textextensions/-/textextensions-2.0.1.tgz";
        sha1 = "be8cf22d65379c151319f88f0335ad8f667abdca";
      };
    };
    "binaryextensions-2.0.0" = {
      name = "binaryextensions";
      packageName = "binaryextensions";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binaryextensions/-/binaryextensions-2.0.0.tgz";
        sha1 = "e597d1a7a6a3558a2d1c7241a16c99965e6aa40f";
      };
    };
    "editions-1.3.3" = {
      name = "editions";
      packageName = "editions";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/editions/-/editions-1.3.3.tgz";
        sha1 = "0907101bdda20fac3cbe334c27cbd0688dc99a5b";
      };
    };
    "commondir-1.0.1" = {
      name = "commondir";
      packageName = "commondir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commondir/-/commondir-1.0.1.tgz";
        sha1 = "ddd800da0c66127393cca5950ea968a3aaf1253b";
      };
    };
    "deep-extend-0.4.1" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.1.tgz";
        sha1 = "efe4113d08085f4e6f9687759810f807469e2253";
      };
    };
    "ejs-2.5.6" = {
      name = "ejs";
      packageName = "ejs";
      version = "2.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ejs/-/ejs-2.5.6.tgz";
        sha1 = "479636bfa3fe3b1debd52087f0acb204b4f19c88";
      };
    };
    "globby-6.1.0" = {
      name = "globby";
      packageName = "globby";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-6.1.0.tgz";
        sha1 = "f5a6d70e8395e21c858fb0489d64df02424d506c";
      };
    };
    "multimatch-2.1.0" = {
      name = "multimatch";
      packageName = "multimatch";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multimatch/-/multimatch-2.1.0.tgz";
        sha1 = "9c7906a22fb4c02919e2f5f75161b4cdbd4b2a2b";
      };
    };
    "vinyl-2.0.1" = {
      name = "vinyl";
      packageName = "vinyl";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl/-/vinyl-2.0.1.tgz";
        sha1 = "1c3b4931e7ac4c1efee743f3b91a74c094407bb6";
      };
    };
    "array-union-1.0.2" = {
      name = "array-union";
      packageName = "array-union";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-union/-/array-union-1.0.2.tgz";
        sha1 = "9a34410e4f4e3da23dea375be5be70f24778ec39";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "array-differ-1.0.0" = {
      name = "array-differ";
      packageName = "array-differ";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-differ/-/array-differ-1.0.0.tgz";
        sha1 = "eff52e3758249d33be402b8bb8e564bb2b5d4031";
      };
    };
    "arrify-1.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz";
        sha1 = "898508da2226f380df904728456849c1501a4b0d";
      };
    };
    "clone-1.0.2" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.2.tgz";
        sha1 = "260b7a99ebb1edfe247538175f783243cb19d149";
      };
    };
    "clone-buffer-1.0.0" = {
      name = "clone-buffer";
      packageName = "clone-buffer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-buffer/-/clone-buffer-1.0.0.tgz";
        sha1 = "e3e25b207ac4e701af721e2cb5a16792cac3dc58";
      };
    };
    "clone-stats-1.0.0" = {
      name = "clone-stats";
      packageName = "clone-stats";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-stats/-/clone-stats-1.0.0.tgz";
        sha1 = "b3782dff8bb5474e18b9b6bf0fdfe782f8777680";
      };
    };
    "cloneable-readable-1.0.0" = {
      name = "cloneable-readable";
      packageName = "cloneable-readable";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cloneable-readable/-/cloneable-readable-1.0.0.tgz";
        sha1 = "a6290d413f217a61232f95e458ff38418cfb0117";
      };
    };
    "remove-trailing-separator-1.0.1" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.0.1.tgz";
        sha1 = "615ebb96af559552d4bf4057c8436d486ab63cc4";
      };
    };
    "replace-ext-1.0.0" = {
      name = "replace-ext";
      packageName = "replace-ext";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/replace-ext/-/replace-ext-1.0.0.tgz";
        sha1 = "de63128373fcbf7c3ccfa4de5a480c45a67958eb";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "read-pkg-2.0.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-2.0.0.tgz";
        sha1 = "8ef1c0623c6a6db0dc6713c4bfac46332b2368f8";
      };
    };
    "load-json-file-2.0.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-2.0.0.tgz";
        sha1 = "7947e42149af80d696cbf797bcaabcfe1fe29ca8";
      };
    };
    "normalize-package-data-2.3.5" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.3.5.tgz";
        sha1 = "8d924f142960e1777e7ffe170543631cc7cb02df";
      };
    };
    "path-type-2.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-2.0.0.tgz";
        sha1 = "f012ccb8415b7096fc2daa1054c3d72389594c73";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "strip-bom-3.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz";
        sha1 = "2334c18e9c759f7bdd56fdef7e9ae3d588e68ed3";
      };
    };
    "error-ex-1.3.1" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.1.tgz";
        sha1 = "f855a86ce61adc4e8621c3cda21e7a7612c3a8dc";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "hosted-git-info-2.2.0" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.2.0.tgz";
        sha1 = "7a0d097863d886c0fabbdcd37bf1758d8becf8a5";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "validate-npm-package-license-3.0.1" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.1.tgz";
        sha1 = "2804babe712ad3379459acfbe24746ab2c303fbc";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "spdx-correct-1.0.2" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-1.0.2.tgz";
        sha1 = "4b3073d933ff51f3912f03ac5519498a4150db40";
      };
    };
    "spdx-expression-parse-1.0.4" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz";
        sha1 = "9bdf2f20e1f40ed447fbe273266191fced51626c";
      };
    };
    "spdx-license-ids-1.2.2" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz";
        sha1 = "c9df7a3424594ade6bd11900d596696dc06bac57";
      };
    };
    "is-promise-2.1.0" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz";
        sha1 = "79a2a9ece7f096e80f36d2b2f3bc16c1ff4bf3fa";
      };
    };
    "interpret-1.0.1" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.0.1.tgz";
        sha1 = "d579fb7f693b858004947af39fa0db49f795602c";
      };
    };
    "rechoir-0.6.2" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.6.2.tgz";
        sha1 = "85204b54dba82d5742e28c96756ef43af50e3384";
      };
    };
    "resolve-1.3.2" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.3.2.tgz";
        sha1 = "1f0442c9e0cbb8136e87b9305f932f46c7f28235";
      };
    };
    "path-parse-1.0.5" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.5.tgz";
        sha1 = "3c1adf871ea9cd6c9431b6ea2bd74a0ff055c4c1";
      };
    };
    "readable-stream-2.2.3" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.2.3.tgz";
        sha1 = "9cf49463985df016c8ae8813097a9293a9b33729";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "diff-2.2.3" = {
      name = "diff";
      packageName = "diff";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-2.2.3.tgz";
        sha1 = "60eafd0d28ee906e4e8ff0a52c1229521033bf99";
      };
    };
    "globby-4.1.0" = {
      name = "globby";
      packageName = "globby";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-4.1.0.tgz";
        sha1 = "080f54549ec1b82a6c60e631fc82e1211dbe95f8";
      };
    };
    "grouped-queue-0.3.3" = {
      name = "grouped-queue";
      packageName = "grouped-queue";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grouped-queue/-/grouped-queue-0.3.3.tgz";
        sha1 = "c167d2a5319c5a0e0964ef6a25b7c2df8996c85c";
      };
    };
    "inquirer-1.2.3" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-1.2.3.tgz";
        sha1 = "4dec6f32f37ef7bb0b2ed3f1d1a5c3f545074918";
      };
    };
    "log-symbols-1.0.2" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-1.0.2.tgz";
        sha1 = "376ff7b58ea3086a0f09facc74617eca501e1a18";
      };
    };
    "mem-fs-1.1.3" = {
      name = "mem-fs";
      packageName = "mem-fs";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mem-fs/-/mem-fs-1.1.3.tgz";
        sha1 = "b8ae8d2e3fcb6f5d3f9165c12d4551a065d989cc";
      };
    };
    "untildify-2.1.0" = {
      name = "untildify";
      packageName = "untildify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz";
        sha1 = "17eb2807987f76952e9c0485fc311d06a826a2e0";
      };
    };
    "glob-6.0.4" = {
      name = "glob";
      packageName = "glob";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-6.0.4.tgz";
        sha1 = "0f08860f6a155127b2fadd4f9ce24b1aab6e4d22";
      };
    };
    "ansi-escapes-1.4.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-1.4.0.tgz";
        sha1 = "d3a8a83b319aa67793662b13e761c7911422306e";
      };
    };
    "cli-cursor-1.0.2" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-1.0.2.tgz";
        sha1 = "64da3f7d56a54412e59794bd62dc35295e8f2987";
      };
    };
    "cli-width-2.1.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-2.1.0.tgz";
        sha1 = "b234ca209b29ef66fc518d9b98d5847b00edf00a";
      };
    };
    "external-editor-1.1.1" = {
      name = "external-editor";
      packageName = "external-editor";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/external-editor/-/external-editor-1.1.1.tgz";
        sha1 = "12d7b0db850f7ff7e7081baf4005700060c4600b";
      };
    };
    "figures-1.7.0" = {
      name = "figures";
      packageName = "figures";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-1.7.0.tgz";
        sha1 = "cbe1e3affcf1cd44b80cadfed28dc793a9701d2e";
      };
    };
    "mute-stream-0.0.6" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.6.tgz";
        sha1 = "48962b19e169fd1dfc240b3f1e7317627bbc47db";
      };
    };
    "rx-4.1.0" = {
      name = "rx";
      packageName = "rx";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rx/-/rx-4.1.0.tgz";
        sha1 = "a5f13ff79ef3b740fe30aa803fb09f98805d4782";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "restore-cursor-1.0.1" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-1.0.1.tgz";
        sha1 = "34661f46886327fed2991479152252df92daa541";
      };
    };
    "exit-hook-1.1.1" = {
      name = "exit-hook";
      packageName = "exit-hook";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit-hook/-/exit-hook-1.1.1.tgz";
        sha1 = "f05ca233b48c05d54fff07765df8507e95c02ff8";
      };
    };
    "onetime-1.1.0" = {
      name = "onetime";
      packageName = "onetime";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-1.1.0.tgz";
        sha1 = "a1f7838f8314c516f05ecefcbc4ccfe04b4ed789";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "spawn-sync-1.0.15" = {
      name = "spawn-sync";
      packageName = "spawn-sync";
      version = "1.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/spawn-sync/-/spawn-sync-1.0.15.tgz";
        sha1 = "b00799557eb7fb0c8376c29d44e8a1ea67e57476";
      };
    };
    "tmp-0.0.29" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.0.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.0.29.tgz";
        sha1 = "f25125ff0dd9da3ccb0c2dd371ee1288bb9128c0";
      };
    };
    "concat-stream-1.6.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.0.tgz";
        sha1 = "0aac662fd52be78964d5532f694784e70110acf7";
      };
    };
    "os-shim-0.1.3" = {
      name = "os-shim";
      packageName = "os-shim";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-shim/-/os-shim-0.1.3.tgz";
        sha1 = "6b62c3791cf7909ea35ed46e17658bb417cb3917";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "vinyl-1.2.0" = {
      name = "vinyl";
      packageName = "vinyl";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl/-/vinyl-1.2.0.tgz";
        sha1 = "5c88036cf565e5df05558bfc911f8656df218884";
      };
    };
    "vinyl-file-2.0.0" = {
      name = "vinyl-file";
      packageName = "vinyl-file";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl-file/-/vinyl-file-2.0.0.tgz";
        sha1 = "a7ebf5ffbefda1b7d18d140fcb07b223efb6751a";
      };
    };
    "clone-stats-0.0.1" = {
      name = "clone-stats";
      packageName = "clone-stats";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-stats/-/clone-stats-0.0.1.tgz";
        sha1 = "b88f94a82cf38b8791d58046ea4029ad88ca99d1";
      };
    };
    "replace-ext-0.0.1" = {
      name = "replace-ext";
      packageName = "replace-ext";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/replace-ext/-/replace-ext-0.0.1.tgz";
        sha1 = "29bbd92078a739f0bcce2b4ee41e837953522924";
      };
    };
    "strip-bom-2.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz";
        sha1 = "6219a85616520491f35788bdbf1447a99c7e6b0e";
      };
    };
    "strip-bom-stream-2.0.0" = {
      name = "strip-bom-stream";
      packageName = "strip-bom-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom-stream/-/strip-bom-stream-2.0.0.tgz";
        sha1 = "f87db5ef2613f6968aa545abfe1ec728b6a829ca";
      };
    };
    "is-utf8-0.2.1" = {
      name = "is-utf8";
      packageName = "is-utf8";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz";
        sha1 = "4b0da1442104d1b336340e80797e865cf39f7d72";
      };
    };
    "first-chunk-stream-2.0.0" = {
      name = "first-chunk-stream";
      packageName = "first-chunk-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/first-chunk-stream/-/first-chunk-stream-2.0.0.tgz";
        sha1 = "1bdecdb8e083c0664b91945581577a43a9f31d70";
      };
    };
    "cli-boxes-1.0.0" = {
      name = "cli-boxes";
      packageName = "cli-boxes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-1.0.0.tgz";
        sha1 = "4fa917c3e59c94a004cd61f8ee509da651687143";
      };
    };
    "pad-component-0.0.1" = {
      name = "pad-component";
      packageName = "pad-component";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pad-component/-/pad-component-0.0.1.tgz";
        sha1 = "ad1f22ce1bf0fdc0d6ddd908af17f351a404b8ac";
      };
    };
    "repeating-2.0.1" = {
      name = "repeating";
      packageName = "repeating";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz";
        sha1 = "5214c53a926d3552707527fbab415dbc08d06dda";
      };
    };
    "taketalk-1.0.0" = {
      name = "taketalk";
      packageName = "taketalk";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/taketalk/-/taketalk-1.0.0.tgz";
        sha1 = "b4d4f0deed206ae7df775b129ea2ca6de52f26dd";
      };
    };
    "wrap-ansi-2.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-2.1.0.tgz";
        sha1 = "d8fc3d284dd05794fe84973caecdd1cf824fdd85";
      };
    };
    "is-finite-1.0.2" = {
      name = "is-finite";
      packageName = "is-finite";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-finite/-/is-finite-1.0.2.tgz";
        sha1 = "cc6677695602be550ef11e8b4aa6305342b6d0aa";
      };
    };
    "get-stdin-4.0.1" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-4.0.1.tgz";
        sha1 = "b968c6b0a04384324902e8bf1a5df32579a450fe";
      };
    };
  };
  args = {
    name = "nix-revealjs";
    packageName = "nix-revealjs";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      (sources."generator-reveal-1.0.0" // {
        dependencies = [
          (sources."chalk-1.1.3" // {
            dependencies = [
              sources."ansi-styles-2.2.1"
              sources."escape-string-regexp-1.0.5"
              (sources."has-ansi-2.0.0" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
              sources."supports-color-2.0.0"
            ];
          })
          sources."lodash-4.17.4"
          sources."semver-5.3.0"
          (sources."underscore.string-3.3.4" // {
            dependencies = [
              sources."sprintf-js-1.0.3"
              sources."util-deprecate-1.0.2"
            ];
          })
          (sources."yeoman-generator-1.1.1" // {
            dependencies = [
              sources."async-2.1.5"
              (sources."class-extend-0.1.2" // {
                dependencies = [
                  sources."object-assign-2.1.1"
                ];
              })
              (sources."cli-table-0.3.1" // {
                dependencies = [
                  sources."colors-1.0.3"
                ];
              })
              (sources."cross-spawn-5.1.0" // {
                dependencies = [
                  (sources."lru-cache-4.0.2" // {
                    dependencies = [
                      sources."pseudomap-1.0.2"
                      sources."yallist-2.0.0"
                    ];
                  })
                  (sources."shebang-command-1.2.0" // {
                    dependencies = [
                      sources."shebang-regex-1.0.0"
                    ];
                  })
                  (sources."which-1.2.12" // {
                    dependencies = [
                      sources."isexe-1.1.2"
                    ];
                  })
                ];
              })
              sources."dargs-5.1.0"
              sources."dateformat-2.0.0"
              (sources."debug-2.6.1" // {
                dependencies = [
                  sources."ms-0.7.2"
                ];
              })
              sources."detect-conflict-1.0.1"
              (sources."error-7.0.2" // {
                dependencies = [
                  sources."string-template-0.2.1"
                  sources."xtend-4.0.1"
                ];
              })
              (sources."find-up-2.1.0" // {
                dependencies = [
                  (sources."locate-path-2.0.0" // {
                    dependencies = [
                      (sources."p-locate-2.0.0" // {
                        dependencies = [
                          sources."p-limit-1.1.0"
                        ];
                      })
                    ];
                  })
                ];
              })
              (sources."github-username-3.0.0" // {
                dependencies = [
                  (sources."gh-got-5.0.0" // {
                    dependencies = [
                      (sources."got-6.7.1" // {
                        dependencies = [
                          (sources."create-error-class-3.0.2" // {
                            dependencies = [
                              sources."capture-stack-trace-1.0.0"
                            ];
                          })
                          sources."duplexer3-0.1.4"
                          sources."get-stream-3.0.0"
                          sources."is-redirect-1.0.0"
                          sources."is-retry-allowed-1.1.0"
                          sources."is-stream-1.1.0"
                          sources."lowercase-keys-1.0.0"
                          sources."safe-buffer-5.0.1"
                          sources."timed-out-4.0.1"
                          sources."unzip-response-2.0.1"
                          (sources."url-parse-lax-1.0.0" // {
                            dependencies = [
                              sources."prepend-http-1.0.4"
                            ];
                          })
                        ];
                      })
                      sources."is-plain-obj-1.1.0"
                    ];
                  })
                ];
              })
              (sources."glob-7.1.1" // {
                dependencies = [
                  sources."fs.realpath-1.0.0"
                  (sources."inflight-1.0.6" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                  sources."inherits-2.0.3"
                  (sources."minimatch-3.0.3" // {
                    dependencies = [
                      (sources."brace-expansion-1.1.6" // {
                        dependencies = [
                          sources."balanced-match-0.4.2"
                          sources."concat-map-0.0.1"
                        ];
                      })
                    ];
                  })
                  (sources."once-1.4.0" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                ];
              })
              (sources."istextorbinary-2.1.0" // {
                dependencies = [
                  sources."textextensions-2.0.1"
                  sources."binaryextensions-2.0.0"
                  sources."editions-1.3.3"
                ];
              })
              (sources."mem-fs-editor-3.0.2" // {
                dependencies = [
                  sources."commondir-1.0.1"
                  sources."deep-extend-0.4.1"
                  sources."ejs-2.5.6"
                  (sources."globby-6.1.0" // {
                    dependencies = [
                      (sources."array-union-1.0.2" // {
                        dependencies = [
                          sources."array-uniq-1.0.3"
                        ];
                      })
                      sources."object-assign-4.1.1"
                      sources."pify-2.3.0"
                      (sources."pinkie-promise-2.0.1" // {
                        dependencies = [
                          sources."pinkie-2.0.4"
                        ];
                      })
                    ];
                  })
                  (sources."multimatch-2.1.0" // {
                    dependencies = [
                      sources."array-differ-1.0.0"
                      (sources."array-union-1.0.2" // {
                        dependencies = [
                          sources."array-uniq-1.0.3"
                        ];
                      })
                      sources."arrify-1.0.1"
                      (sources."minimatch-3.0.3" // {
                        dependencies = [
                          (sources."brace-expansion-1.1.6" // {
                            dependencies = [
                              sources."balanced-match-0.4.2"
                              sources."concat-map-0.0.1"
                            ];
                          })
                        ];
                      })
                    ];
                  })
                  (sources."vinyl-2.0.1" // {
                    dependencies = [
                      sources."clone-1.0.2"
                      sources."clone-buffer-1.0.0"
                      sources."clone-stats-1.0.0"
                      (sources."cloneable-readable-1.0.0" // {
                        dependencies = [
                          sources."inherits-2.0.3"
                          sources."process-nextick-args-1.0.7"
                        ];
                      })
                      sources."is-stream-1.1.0"
                      sources."remove-trailing-separator-1.0.1"
                      sources."replace-ext-1.0.0"
                    ];
                  })
                ];
              })
              sources."minimist-1.2.0"
              (sources."mkdirp-0.5.1" // {
                dependencies = [
                  sources."minimist-0.0.8"
                ];
              })
              sources."path-exists-3.0.0"
              sources."path-is-absolute-1.0.1"
              sources."pretty-bytes-4.0.2"
              (sources."read-chunk-2.0.0" // {
                dependencies = [
                  sources."pify-2.3.0"
                ];
              })
              (sources."read-pkg-up-2.0.0" // {
                dependencies = [
                  (sources."read-pkg-2.0.0" // {
                    dependencies = [
                      (sources."load-json-file-2.0.0" // {
                        dependencies = [
                          sources."graceful-fs-4.1.11"
                          (sources."parse-json-2.2.0" // {
                            dependencies = [
                              (sources."error-ex-1.3.1" // {
                                dependencies = [
                                  sources."is-arrayish-0.2.1"
                                ];
                              })
                            ];
                          })
                          sources."pify-2.3.0"
                          sources."strip-bom-3.0.0"
                        ];
                      })
                      (sources."normalize-package-data-2.3.5" // {
                        dependencies = [
                          sources."hosted-git-info-2.2.0"
                          (sources."is-builtin-module-1.0.0" // {
                            dependencies = [
                              sources."builtin-modules-1.1.1"
                            ];
                          })
                          (sources."validate-npm-package-license-3.0.1" // {
                            dependencies = [
                              (sources."spdx-correct-1.0.2" // {
                                dependencies = [
                                  sources."spdx-license-ids-1.2.2"
                                ];
                              })
                              sources."spdx-expression-parse-1.0.4"
                            ];
                          })
                        ];
                      })
                      (sources."path-type-2.0.0" // {
                        dependencies = [
                          sources."pify-2.3.0"
                        ];
                      })
                    ];
                  })
                ];
              })
              sources."rimraf-2.6.1"
              (sources."run-async-2.3.0" // {
                dependencies = [
                  sources."is-promise-2.1.0"
                ];
              })
              (sources."shelljs-0.7.6" // {
                dependencies = [
                  sources."interpret-1.0.1"
                  (sources."rechoir-0.6.2" // {
                    dependencies = [
                      (sources."resolve-1.3.2" // {
                        dependencies = [
                          sources."path-parse-1.0.5"
                        ];
                      })
                    ];
                  })
                ];
              })
              sources."text-table-0.2.0"
              (sources."through2-2.0.3" // {
                dependencies = [
                  (sources."readable-stream-2.2.3" // {
                    dependencies = [
                      sources."buffer-shims-1.0.0"
                      sources."core-util-is-1.0.2"
                      sources."isarray-1.0.0"
                      sources."inherits-2.0.3"
                      sources."process-nextick-args-1.0.7"
                      sources."string_decoder-0.10.31"
                      sources."util-deprecate-1.0.2"
                    ];
                  })
                  sources."xtend-4.0.1"
                ];
              })
              (sources."user-home-2.0.0" // {
                dependencies = [
                  sources."os-homedir-1.0.2"
                ];
              })
              (sources."yeoman-environment-1.6.6" // {
                dependencies = [
                  sources."diff-2.2.3"
                  sources."escape-string-regexp-1.0.5"
                  (sources."globby-4.1.0" // {
                    dependencies = [
                      (sources."array-union-1.0.2" // {
                        dependencies = [
                          sources."array-uniq-1.0.3"
                        ];
                      })
                      sources."arrify-1.0.1"
                      (sources."glob-6.0.4" // {
                        dependencies = [
                          (sources."inflight-1.0.6" // {
                            dependencies = [
                              sources."wrappy-1.0.2"
                            ];
                          })
                          sources."inherits-2.0.3"
                          (sources."minimatch-3.0.3" // {
                            dependencies = [
                              (sources."brace-expansion-1.1.6" // {
                                dependencies = [
                                  sources."balanced-match-0.4.2"
                                  sources."concat-map-0.0.1"
                                ];
                              })
                            ];
                          })
                          (sources."once-1.4.0" // {
                            dependencies = [
                              sources."wrappy-1.0.2"
                            ];
                          })
                        ];
                      })
                      sources."object-assign-4.1.1"
                      sources."pify-2.3.0"
                      (sources."pinkie-promise-2.0.1" // {
                        dependencies = [
                          sources."pinkie-2.0.4"
                        ];
                      })
                    ];
                  })
                  sources."grouped-queue-0.3.3"
                  (sources."inquirer-1.2.3" // {
                    dependencies = [
                      sources."ansi-escapes-1.4.0"
                      (sources."cli-cursor-1.0.2" // {
                        dependencies = [
                          (sources."restore-cursor-1.0.1" // {
                            dependencies = [
                              sources."exit-hook-1.1.1"
                              sources."onetime-1.1.0"
                            ];
                          })
                        ];
                      })
                      sources."cli-width-2.1.0"
                      (sources."external-editor-1.1.1" // {
                        dependencies = [
                          sources."extend-3.0.0"
                          (sources."spawn-sync-1.0.15" // {
                            dependencies = [
                              (sources."concat-stream-1.6.0" // {
                                dependencies = [
                                  sources."inherits-2.0.3"
                                  sources."typedarray-0.0.6"
                                  (sources."readable-stream-2.2.3" // {
                                    dependencies = [
                                      sources."buffer-shims-1.0.0"
                                      sources."core-util-is-1.0.2"
                                      sources."isarray-1.0.0"
                                      sources."process-nextick-args-1.0.7"
                                      sources."string_decoder-0.10.31"
                                      sources."util-deprecate-1.0.2"
                                    ];
                                  })
                                ];
                              })
                              sources."os-shim-0.1.3"
                            ];
                          })
                          (sources."tmp-0.0.29" // {
                            dependencies = [
                              sources."os-tmpdir-1.0.2"
                            ];
                          })
                        ];
                      })
                      (sources."figures-1.7.0" // {
                        dependencies = [
                          sources."object-assign-4.1.1"
                        ];
                      })
                      sources."mute-stream-0.0.6"
                      (sources."pinkie-promise-2.0.1" // {
                        dependencies = [
                          sources."pinkie-2.0.4"
                        ];
                      })
                      sources."rx-4.1.0"
                      (sources."string-width-1.0.2" // {
                        dependencies = [
                          sources."code-point-at-1.1.0"
                          (sources."is-fullwidth-code-point-1.0.0" // {
                            dependencies = [
                              sources."number-is-nan-1.0.1"
                            ];
                          })
                        ];
                      })
                      (sources."strip-ansi-3.0.1" // {
                        dependencies = [
                          sources."ansi-regex-2.1.1"
                        ];
                      })
                      sources."through-2.3.8"
                    ];
                  })
                  sources."log-symbols-1.0.2"
                  (sources."mem-fs-1.1.3" // {
                    dependencies = [
                      (sources."vinyl-1.2.0" // {
                        dependencies = [
                          sources."clone-1.0.2"
                          sources."clone-stats-0.0.1"
                          sources."replace-ext-0.0.1"
                        ];
                      })
                      (sources."vinyl-file-2.0.0" // {
                        dependencies = [
                          sources."graceful-fs-4.1.11"
                          sources."pify-2.3.0"
                          (sources."pinkie-promise-2.0.1" // {
                            dependencies = [
                              sources."pinkie-2.0.4"
                            ];
                          })
                          (sources."strip-bom-2.0.0" // {
                            dependencies = [
                              sources."is-utf8-0.2.1"
                            ];
                          })
                          (sources."strip-bom-stream-2.0.0" // {
                            dependencies = [
                              (sources."first-chunk-stream-2.0.0" // {
                                dependencies = [
                                  (sources."readable-stream-2.2.3" // {
                                    dependencies = [
                                      sources."buffer-shims-1.0.0"
                                      sources."core-util-is-1.0.2"
                                      sources."isarray-1.0.0"
                                      sources."inherits-2.0.3"
                                      sources."process-nextick-args-1.0.7"
                                      sources."string_decoder-0.10.31"
                                      sources."util-deprecate-1.0.2"
                                    ];
                                  })
                                ];
                              })
                            ];
                          })
                        ];
                      })
                    ];
                  })
                  (sources."untildify-2.1.0" // {
                    dependencies = [
                      sources."os-homedir-1.0.2"
                    ];
                  })
                ];
              })
            ];
          })
          (sources."yosay-1.2.1" // {
            dependencies = [
              sources."ansi-regex-2.1.1"
              sources."ansi-styles-2.2.1"
              sources."cli-boxes-1.0.0"
              sources."pad-component-0.0.1"
              (sources."repeating-2.0.1" // {
                dependencies = [
                  (sources."is-finite-1.0.2" // {
                    dependencies = [
                      sources."number-is-nan-1.0.1"
                    ];
                  })
                ];
              })
              (sources."string-width-1.0.2" // {
                dependencies = [
                  sources."code-point-at-1.1.0"
                  (sources."is-fullwidth-code-point-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.1"
                    ];
                  })
                ];
              })
              sources."strip-ansi-3.0.1"
              (sources."taketalk-1.0.0" // {
                dependencies = [
                  sources."get-stdin-4.0.1"
                  sources."minimist-1.2.0"
                ];
              })
              sources."wrap-ansi-2.1.0"
            ];
          })
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Simple meta-package for NPM to build reveal.js presentations in a nix-based environment";
      license = "MIT";
    };
    production = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}